name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      rust: [stable, beta]
      include:
        - os: ubuntu-latest
          netmap: true
        - os: macos-latest
          netmap: false
        - os: windows-latest
          netmap: false
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Netmap (Linux)
        if: matrix.netmap
        run: |
          sudo apt-get update
          sudo apt-get install -y netmap libnetmap-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchains: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Rust tests
        run: cargo test --all-features
      
  bench:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Install Netmap
        run: |
          sudo apt-get update
          sudo apt-get install -y netmap libnetmap-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run benchmarks
        run: cargo bench --features=sys