name: CI

on:
  push:
  pull_request:

env:
  NETMAP_LOCATION: /usr/local
  DISABLE_NETMAP_KERNEL: "1"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            netmap: true
          - os: macos-latest
            netmap: false
          - os: windows-latest
            netmap: false

    steps:
      - uses: actions/checkout@v3

      # Netmap only on Ubuntu
      - if: matrix.netmap
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libelf-dev pkg-config

      - if: matrix.netmap
        id: netmap-cache
        uses: actions/cache@v3
        with:
          path: netmap
          key: netmap-${{ runner.os }}-${{ github.run_id }}

      - if: matrix.netmap && steps.netmap-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/luigirizzo/netmap.git netmap
          cd netmap
          make
          sudo make install

      - if: matrix.netmap && steps.netmap-cache.outputs.cache-hit == 'true'
        run: echo "Using cached Netmap build"

      # Rust toolchain & linting
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

      # Tests: fallback-only on non-Linux; full on Linux
      - name: Run fallback‐only tests
        if: matrix.netmap == false
        run: cargo test

      - name: Run full tests with Netmap
        if: matrix.netmap == true
        run: cargo test --all-features

  bench:
    needs: test
    runs-on: ubuntu-latest
    env:
      NETMAP_LOCATION: /usr/local
      DISABLE_NETMAP_KERNEL: "1"

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libelf-dev pkg-config

      - id: netmap-cache
        uses: actions/cache@v3
        with:
          path: netmap
          key: netmap-${{ runner.os }}-${{ github.run_id }}

      - if: steps.netmap-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/luigirizzo/netmap.git netmap
          cd netmap
          make
          sudo make install

      - if: steps.netmap-cache.outputs.cache-hit == 'true'
        run: echo "Using cached Netmap build"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo bench --features=sys
