name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            netmap: true
          - os: macos-latest
            netmap: false
          - os: windows-latest
            netmap: false

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Netmap (Ubuntu only)
        if: matrix.netmap == true
        run: |
          sudo apt-get update
          sudo apt-get install -y netmap libnetmap-dev

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchains: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Verify formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

  bench:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Netmap
        run: |
          sudo apt-get update
          sudo apt-get install -y netmap libnetmap-dev

      - name: Set up Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchains: stable
          override: true

      - name: Run benchmarks
        run: cargo bench --features=sys
