name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            netmap: true
          - os: macos-latest
            netmap: false
          - os: windows-latest
            netmap: false

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # === Netmap (Ubuntu only) ===
      - name: Install Netmap prerequisites
        if: matrix.netmap == true
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libelf-dev pkg-config

      - name: Cache Netmap build
        if: matrix.netmap == true
        id: netmap-cache
        uses: actions/cache@v3
        with:
          path: netmap
          key: netmap-${{ runner.os }}-${{ github.run_id }}

      - name: Build & install Netmap
        if: matrix.netmap == true && steps.netmap-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/luigirizzo/netmap.git netmap
          cd netmap
          make
          sudo make install

      - name: Reuse cached Netmap
        if: matrix.netmap == true && steps.netmap-cache.outputs.cache-hit == 'true'
        run: echo "Using cached Netmap build"

      # === Rust setup ===
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Verify formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

  bench:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # === Netmap (Ubuntu only) ===
      - name: Install Netmap prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libelf-dev pkg-config

      - name: Cache Netmap build
        id: netmap-cache
        uses: actions/cache@v3
        with:
          path: netmap
          key: netmap-${{ runner.os }}-${{ github.run_id }}

      - name: Build & install Netmap
        if: steps.netmap-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/luigirizzo/netmap.git netmap
          cd netmap
          make
          sudo make install

      - name: Reuse cached Netmap
        if: steps.netmap-cache.outputs.cache-hit == 'true'
        run: echo "Using cached Netmap build"

      # === Rust setup for benchmarks ===
      - name: Set up Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run benchmarks
        run: cargo bench --features=sys
